stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: docker:20.10.24  # version stable avec docker
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"  # obligatoire pour docker:dind
  script:
    - docker info
    - docker build -t devops-app .
  only:
    - feature/ci-pipeline
    - develop
